DROP TABLE IF EXISTS info_quiz
DROP TABLE IF EXISTS dati_quiz
CREATE TABLE info_quiz ("NOME QUIZ" TEXT,"NOME CORSO" TEXT, "APERTURA" TEXT)
CREATE TABLE dati_quiz ("NOME QUIZ" TEXT, Q INTEGER, "TIPO DI DOMANDA" TEXT, "NOME DOMANDA" TEXT, TENTATIVI INTEGER, "INDICE DI ABILITA" TEXT, "DEVIAZIONE STANDARD" TEXT, "INDICE DELLE RISPOSTE DATE A CASO" TEXT, "PESO PREVISTO" TEXT, "PESO EFFETTIVO" TEXT, "INDICE DI DISCRIMINAZIONE" TEXT, "EFFICIENZA DISCRIMINANTE" TEXT)